CREATE TABLE pokemons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pokedex_num INTEGER NOT NULL UNIQUE CHECK (pokedex_num BETWEEN 1 AND 150),
  nombre VARCHAR(100) NOT NULL CHECK (length(trim(nombre)) > 0),
  tipo_1 VARCHAR(30) NOT NULL CHECK (length(trim(tipo_1)) > 0),
  tipo_2 VARCHAR(30),
  altura_m NUMERIC(5, 2) CHECK (altura_m IS NULL OR altura_m >= 0),
  peso_kg NUMERIC(6, 2) CHECK (peso_kg IS NULL OR peso_kg >= 0),
  descripcion TEXT DEFAULT '',
  sprite_url TEXT,
  hp INTEGER CHECK (hp IS NULL OR hp BETWEEN 0 AND 255),
  ataque INTEGER CHECK (ataque IS NULL OR ataque BETWEEN 0 AND 255),
  defensa INTEGER CHECK (defensa IS NULL OR defensa BETWEEN 0 AND 255),
  velocidad INTEGER CHECK (velocidad IS NULL OR velocidad BETWEEN 0 AND 255)
);
